source 'http://rubygems.org'
#gem 'nyulibraries-assets', :require => 'nyulibraries-assets' , github: 'NYULibraries/nyulibraries-assets', tag: 'v4.2.1'
#gem 'nyulibraries-assets', :require => 'nyulibraries-assets' , :git => 'git://github.com/NYULibraries/nyulibraries-assets.git'

gem 'compass', '~> 0.12.2'
gem 'nyulibraries-assets', github: 'NYULibraries/nyulibraries-assets', tag: 'v3.2.4'
gem 'microservice_precompiler'
gem 'rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'capistrano','~> 2.15'
gem 'railsless-deploy'
gem 'siteleaf'
gem 'liquid'
gem 'formaggio', github: 'NYULibraries/formaggio'
