---
exclude:
- assets/js/src/
- node_modules/
permalink: pretty
kramdown:
  input: GFM
sass:
  style: ":compressed"
twitter: nyu
facebook: nyu
page_size: 10
swiftype:
  install_key: P-UkfFsFPrNCmsHxgrtG
  engine_key: TTbssqxzRGDAfQzB5JiU
main_menu:
  About: "/about"
  Locations: "/locations"
  Services: "/services"
secondary_menu:
  My Account: "#todo"
  Ask a Librarian: "/ask"
ask_librarian_menu:
  Chat with us: https://us.libraryh3lp.com/chat/askbobst@chat.libraryh3lp.com?skin=10977&theme=gota&title=Ask+NYU+Libraries&identity=AskBobst
  Email us: "#todo"
  Call us: "#todo"
  Visit: "#todo"
  Schedule a Consultation: "#todo"
footer_left_menu:
  About the Libraries: "/about"
  Departments: "/departments"
  Find a Space: "/spaces"
  Staff Directory: "/people"
footer_right_menu:
  Research Guides: "#todo"
  FAQs: "#todo"
  Careers at NYU Libraries: "#todo"
  Contact: "#todo"
google_tag_manager_key: GTM-59RTPM
title: New York University Division of Libraries
url: http://dev.library.nyu.edu
timezone: Eastern Time (US & Canada)
collections:
  uploads:
    title: Uploads
    output: true
  departments:
    title: departments
    output: true
    permalink: "/:collection/:path/"
  forms:
    title: forms
    output: true
  locations:
    title: locations
    output: true
    permalink: "/:collection/:path/"
  people:
    title: people
    output: true
    permalink: "/:collection/:path/"
  services:
    title: services
    output: true
    permalink: "/:collection/:path/"
  spaces:
    title: spaces
    output: true
    permalink: "/:collection/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: article
- scope:
    path: style-guide
  values:
    sitemap: false
    layout: style_guide
    custom_css: style-guide
