# Site settings
title: New York University Libraries
url: "http://dev.library.nyu.edu" # the base hostname & protocol for your site

# Build settings
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

exclude: [assets/js/src/, node_modules/]
sass:
  style: :compressed

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "article"
  - scope:
      path: "style-guide"
    values:
      sitemap: false
      layout: "style_guide"
      custom_css: style-guide

# These settings should come from Siteleaf
twitter: nyu
facebook: nyu
newsletter: "#todo"
privacy_policy: "#todo"
giving_to_libraries_url: "#todo"

page_size: 10

swiftype:
  install_key: "P-UkfFsFPrNCmsHxgrtG"
  engine_key: "TTbssqxzRGDAfQzB5JiU"

collections:
  departments:
    output: true
    permalink: /:collection/:path/
  locations:
    output: true
    permalink: /:collection/:path/
  spaces:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/

main_menu:
  About: /about
  Locations: /locations
  Services: /services

secondary_menu:
  My Account: "#todo"
  Ask a Librarian: /ask

# account_menu:
#   e-Shelf: http://eshelf.library.nyu.edu
#   Library account: http://eshelf.library.nyu.edu/account
#   E-ZBorrow: http://library.nyu.edu/ezborrow
#   Interlibrary loan (ILL): http://ill.library.nyu.edu

ask_librarian_menu:
  Chat with us: "https://us.libraryh3lp.com/chat/askbobst@chat.libraryh3lp.com?skin=10977&theme=gota&title=Ask+NYU+Libraries&identity=AskBobst"
  Email us: "#todo"
  Call us: "#todo"
  Visit: "#todo"
  Schedule a Consultation: "#todo"


footer_left_menu:
  About the Libraries: /about
  Departments: /departments
  Find a Space: /spaces
  Staff Directory: /people

footer_right_menu:
  Research Guides: "#todo"
  FAQs: "#todo"
  Careers at NYU Libraries: "#todo"
  Contact: "#todo"