file_start      : "---\n\n"
title           : "single"
new_line1       : "\n"
location        : "single"
space           : "single"
new_line2       : "\n"
email           : "single"
twitter         : "single"
blog            : "single"
rss             : "single"
new_line3       : "\n"
libcal_id       : "single"
libanswers_id   : "single"
new_line4       : "\n"
links           : "list"
new_line5       : "\n"
assets          : "assets"
file_end        : "\n---\n\n## "
What We Do      : "block"