docker-defaults: &docker-defaults
  docker:
    - image: docker:18.05.0-ce-git
  working_directory: ~/app

setup: &setup
  run:
    name: Install dependencies
    command: |
      apk add --no-cache python3
      pip3 install docker-compose==1.16.1

build: &build
  run:
    name: Build
    command: |
      docker-compose build

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *setup
      - <<: *test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
