docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

build: &build
  run:
    name: Build
    command: |
      docker-compose build

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

version: 2
jobs:
  build-and-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
