# Yaml file to correct locations in people.
# Format Original: Replace
15 East 84th Street:              Institute for the Study of the Ancient World Library
20 Cooper Square:                 Cooper Union Library
269 Mercer Street:                Courant Institute of Mathematical Sciences Library
5 Metrotech Center:               Bern Dibner Library
Bobst Library:                    Elmer Holmes Bobst Library
Henry Kaufman Management Ctr:     Kaufman Management Center
Institute of Fine Arts:           Institute of Fine Arts Library
Joseph And Violet Pless Hall:     Joseph & Violet Pless Building
Press Annex:                      Pless Annex
SCPS Midtown Center:              SPS Jack Brause Library
Silver Center:                    Silver Center for Arts and Science
Warren Weaver Hall:               Courant Institute of Mathematical Sciences Library