file_start      : "---\n\n"
title           : "single"
subtitle        : "single"
new_line1       : "\n"
type            : "single"
new_line2       : "\n"
address         : "multi-line"
city            : "single"
country         : "single"
coordinates     : "single"
new_line3       : "\n"
email           : "single"
phone           : "single"
new_line4       : "\n"
twitter         : "single"
facebook        : "single"
blog            : "instance"
new_line5       : "\n"
libcal_id       : "single"
libcal_truncated: "boolean"
libcal_link     : "single"
libanswers_id   : "single"
new_line6       : "\n"
links           : "instance"
new_line7       : "\n"
image           : "single"
new_line8       : "\n"
keywords        : "list"
file_end        : "\n---\n\n"
hash            : "# "
About           : "block"