file_start      : "---\n\n"
title           : "list"
# net_id          : "single"
subtitle        : "single"
job_title       : "single"
new_line1       : "\n"
location        : "single"
space           : "single"
departments     : "list"
new_line2       : "\n"
status          : "single"
expertise       : "list"
new_line3       : "\n"
email           : "single"
phone           : "single"
twitter         : "single"
new_line4       : "\n"
image           : "single"
buttons         : "instance"
new_line6       : "\n"
guides          : "instance"
new_line8       : "\n"
publications    : "instance"
new_line9       : "\n"
keywords        : "list"
file_end        : "\n---\n\n"
hash            : "# "
About           : "block"