file_start      : "---\n\n"
title           : "single"
job_title       : "single"
new_line1       : "\n"
type            : "single"
new_line2       : "\n"
location        : "single"
space           : "single"
departments     : "single"
new_line3       : "\n"
status          : "single"
expertise       : "list"
new_line4       : "\n"
email           : "single"
phone           : "single"
new_line5       : "\n"
twitter         : "single"
facebook        : "single"
new_line6       : "\n"
assets          : "assets"
file_end        : "\n---\n\n"
hash            : "## "
About           : "block"