file_start      : "---\n\n"
title           : "single"
new_line1       : "\n"
location        : "single"
space           : "single"
departments     : "list"
new_line2       : "\n"
type            : "single"
topics          : "list"
new_line3       : "\n"
access          : "list"
new_line4       : "\n"
email           : "single"
phone           : "single"
new_line5       : "\n"
twitter         : "single"
blog            : "instance"
new_line6       : "\n"
libcal_id       : "single"
libanswers_id   : "single"
new_line7       : "\n"
links           : "instance"
new_line8       : "\n"
image           : "single"
new_line9       : "\n"
buttons         : "single"
new_line10      : "\n"
keywords        : "list"
file_end        : "\n---\n\n"
hash            : "# "
Services        : "block"