file_start      : "---\n\n"
title           : "single"
new_line1       : "\n"
location        : "single"
space           : "single"
departments     : "list"
new_line2       : "\n"
topics          : "list"
new_line3       : "\n"
access          : "list"
new_line4       : "\n"
email           : "single"
phone           : "single"
new_line5       : "\n"
twitter         : "single"
facebook        : "single"
blog            : "single"
rss             : "single"
new_line6       : "\n"
libcal_id       : "single"
libanswers_id   : "single"
new_line7       : "\n"
links           : "list"
new_line8       : "\n"
assets          : "assets"
file_end        : "\n---\n\n## "
Service         : "block"