file_start      : "---\n\n"
title           : "single"
new_line1       : "\n"
location        : "single"
new_line2       : "\n"
address         : "single"
email           : "single"
phone           : "single"
new_line3       : "\n"
amenities       : "list"
new_line4       : "\n"
libcal_id       : "single"
libanswers_id   : "single"
new_line5       : "\n"
links           : "list"
new_line6       : "\n"
assets          : "assets"
file_end        : "\n---\n\n"
hash            : "## "
About           : "block"