file_start      : "---\n\n"
title           : "single"
subtitle        : "single"
new_line1       : "\n"
location        : "single"
new_line2       : "\n"
address         : "single"
email           : "single"
phone           : "single"
new_line3       : "\n"
type            : "single"
amenities       : "list"
access          : "list"
new_line4       : "\n"
libcal_id       : "single"
libanswers_id   : "single"
new_line5       : "\n"
links           : "instance"
new_line6       : "\n"
image           : "single"
new_line7       : "\n"
keywords        : "list"
file_end        : "\n---\n\n"
hash            : "# "
About           : "block"